# -*- coding: utf-8 -*-
"""assignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y2pkwRDU-e65DFQSzP8LENor1lKrSusP
"""

import numpy as np
import matplotlib.pyplot as plt

vec = np.array([3,4,5,2])
s=2
print(vec*s)

vecList = np.array([1,2])
s1 = 2
s2 = .5
s3 = -1

plt.plot([0,vecList[0]], [0,vecList[1]], 'bs-')
plt.axis('square')
plt.xlim([-4,4])
plt.ylim([-4,4])

